server:
  servlet:
    context-path: /

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        highlight_sql: true #
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

springdoc:
  api-docs.path: /api-docs
  swagger-ui.path: /swagger-ui.html
  swagger-ui.operationsSorter: method
  swagger-ui.tagsSorter: alpha


app:
  crypto:
    aesKeyBase64: QxM6t9K4jUyyBfQpXEQV9xsp4X9SkS2A6nx3y5Ab+7c=
  paging:
    defaultSize: 20
    maxSize: 200
  account:
    system-account-seq: 1
    fee-account-seq: 2
    default-fee-policy-seq: 1
    default-bank-code: "999"
    default-branch-code: "001"
    default-daily-transfer-limit: 3000000
    default-daily-withdraw-limit: 1000000