spring:
  datasource:
    url: jdbc:mysql://db:3306/remittance?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: remittance
    password: remittancepass

  flyway:
    clean-disabled: true